kind: Namespace
apiVersion: v1
metadata:
  name: cgomez-3
  labels:
    name: cgomez-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgomez-3-deployment
  namespace: cgomez-3
  labels:
    app: cgomez-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgomez-3
  template:
    metadata:
      labels:
        app: cgomez-3
    spec:
      nodeSelector:
        purpose: general
      containers:
        - name: cgomez-3
          image: charlie83gs/page:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cgomez-3-service
  namespace: cgomez-3
spec:
  selector:
    app: cgomez-3
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cgomez-3
  namespace: cgomez-3
spec:
  hosts:
    - '*'
  gateways:
    - istio-custom/devops-gateway
  http:
    - name: 'cgomez-3-routes'
      match:
        - uri:
            prefix: '/cgomez-3'
      route:
        - destination:
            host: cgomez-3-service.cgomez-3.svc.cluster.local